### PR TITLE
Issue #2662540 by yanniboi: Started to move CountryConstraintValidato…

### PR DESCRIPTION
**Pull request by yanniboi**
…rTest to KernelTestBase.

Following issue on d.o:
https://www.drupal.org/node/2662540

### CODE REVIEW

**Comment by yanniboi** [comment]
This is just a start. Not tested yet...

**Comment by yanniboi** [comment]
I've updated the class and this is now passing tests. But I think this is a very symfony-ish way of testing the contraints and I think we can find a more Drupally way of testing this...

**Comment by yanniboi** [comment]
Ooo.. Also Travis is currently only testing simpletest, not phpunit tests.

**Comment by yanniboi** [comment]
Looks like this pull request has diverged slightly with me wanting to test the phpunit tests. 

I am happy to tidy up before merge.

**Comment by jamiehollerndigirati** [comment]
Any progress on this?

**Comment by bojanz** [comment]
Fixed in 436f4f45c86e1c041110f05f9cfb35ac317f9f52.

**Pull request closed without merging**
