### PR TITLE
#2753403 Convert AddressFormatTest and ZoneTest to BrowserTestBase

### PR DESCRIPTION
**Pull request by GoZOo**
Work in progress, i still have to deal with previous
```
$this->drupalPostAjaxForm(NULL, $country_values, 'members[0][form][country_code]');
```

I edit to ```submitForm()``` but it fails and i think we should use some FunctionalJavascript tests instead.

### CODE REVIEW

**Comment by bojanz** [comment]
You're right, ZoneTest needs to be a FunctionJavaScript test after all.

**Comment by GoZOo** [comment]
Previous is the last commit for this conversion.

Commited from Milano Airport Departures, so it's still under Dev Days \o/

**Comment by GoZOo** [comment]
Tests for ZoneTest should fail until travis is updated to work with phantomjs

**Comment by bojanz** [comment]
Squashed into 3 commits, merged.

**Pull request closed without merging**
